version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/exemple-ui-front"
      - "/exemple-ui-stub"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
    groups:
      security-dependencies:
        applies-to: security-updates
        patterns:
          - "*"
    commit-message:
      prefix: "[prod]"
      prefix-development: "[dev]"
