name: build
on:
- push
- pull_request
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v3
      -  name: Get npm cache directory
         id: npm-cache-dir
         run: |
           echo "::set-output name=dir::$(npm config get cache)"
      -  uses: actions/cache@v3
         id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
         with:
           path: ${{ steps.npm-cache-dir.outputs.dir }}
           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
           restore-keys: |
            ${{ runner.os }}-node-
      -  name: Use Node.js 16.18.0
         uses: actions/setup-node@v1
         with:
            node-version: 16.18.0
      -  name: install
         working-directory: exemple-ui-front
         run: npm ci
      -  name: build
         working-directory: exemple-ui-front
         run: npm run-script build
      -  name: test
         working-directory: exemple-ui-front
         run: npm run-script test
      -  uses: codecov/codecov-action@v1